[dependencies]
fastapi='0'
[basic]
language = "python"
arch = "mvc"
type="api"
folders=["src/models", "src/controller", "src/services", "src/utils"]
[openai]
api_key = ""
model="gpt-3.5-turbo"
api_base="https://api.openai.com/v1"
temperature=0.5
[api]
style="restful"
