[dependencies]
express='4'
sequelize='6'
[basic]
language = "javascript"
arch = "mvc"
type="api"
db="sqlite"
[openai]
api_key = ""
model="gpt-4"
api_base=""
temperature=0.5
[api]
style="restful"
[db]
need_migration_file=true
[db.sqlite]
uri="./db.sqlite"
dbname="todos"

