[dependencies]
express='4'
[basic]
language = "javascript"
arch = "mvc"
type="api"
db="sqlite"
[openai]
api_key = ""
model="gpt-4"
temperature=0.5
[api]
style="restful"
[db]
need_migration_file=true
[db.sqlite]
uri='./db.sqlite'

